name: Build and Create Standalone EXE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core 7.0.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.101

      - name: Build the project
        run: dotnet build --configuration Release
      
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
            name: OutlookSorter
            path: ./app

